---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: npm-install
  image: node:8-alpine
  commands: ["npm install"]

- name: eslint
  image: marcbachmann/eslint:4.19.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: test-node-8
  image: node:8-alpine
  commands: ["npm run test:ci -s"]

- name: test-node-10
  image: node:10-alpine
  commands: ["npm run test:ci -s"]

- name: set-build-metadata
  image: node:10
  commands: ["npx set-ci"]

- name: pre-release
  image: docker:git
  commands: ["git fetch --tags"]

- name: release
  image: marcbachmann/semantic-release:15.1.3
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]
---
kind: signature
hmac: 54a5ce64be06533caf06d0d6114d841973267cc93f6c236bfa47df0b7926c765

...
