clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

cache: [".npm"]

pipeline:
  npm-install:
    group: install
    image: node:8-alpine
    commands: ["npm install"]

  eslint:
    group: install
    image: marcbachmann/eslint:4.19.1
    secrets: [gh_token]

  npm-ls:
    group: test
    image: node:8-alpine
    commands: ["npm ls -s"]

  test:
    group: test
    image: node:8-alpine
    commands: ["npm run test:ci -s"]

  release:
    group: publish
    image: marcbachmann/semantic-release:15.1.3
    secrets: [gh_token, npm_token]
    when:
      event: push
